services:
  db:
    image: postgres:16-alpine
    container_name: tsa_db
    restart: unless-stopped
    command: ["postgres", "-c", "password_encryption=md5"]
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    networks:
      - tsa-network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}'
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: tsa_django:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tsa_backend
    restart: unless-stopped
    networks:
      - tsa-network
    env_file: .env
    ports:
      - ${PORT_NR}:${PORT_NR}
    environment:
      MODE: ${MODE}
      DEBUG_ENABLED: ${DEBUG}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      APP_PORT: ${PORT_NR}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS}
      # CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    volumes:
    # Enables live code updates during development:
      - .:/app
    # Allows Django to write static and media files to the host
      - django_staticfiles:/app/src/staticfiles
      - django_mediafiles:/app/src/media
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
  django_staticfiles:
  django_mediafiles:

networks:
  tsa-network:
    driver: bridge
