upstream django_backend {
    server backend:8040;
}

server {
    listen 80;
    server_name localhost;

    # Serve Static Files Directly Through Nginx
    location /static/ {
        alias /app/src/staticfiles/;
    }

    # Serve Media Files Directly Through Nginx
    location /media/ {
        alias /app/src/media/;
    }

    # Forward everything else to Gunicorn
    location / {
        # proxy_redirect off;
        proxy_pass http://backend:8040;
        proxy_set_header Host $host:$server_port; # Übergibt 'localhost:8040' an Django
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
